###########################################################
# Change default prefix
###########################################################
unbind C-b
set -g prefix C-a
bind C-a send-prefix

###########################################################
# Options
###########################################################
# Set terminal color support
set -g default-terminal "tmux-256color"
set -ga terminal-features "*:RGB"

set -g mouse on              # Enable mouse support
set -g focus-events on       # Enable focus events for better Neovim integration
set -g escape-time 0         # Disable waiting time when pressing escape for smoother Neovim usage
set -g display-time 2000     # Show tmux messages for 2 seconds
set -g history-limit 5000    # Set scrollback to 5000 lines

# Start window numbering from 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

###########################################################
# Keybinds
###########################################################
# -n: no prefix needed

# Window switching and management
bind -n M-down confirm-before -p "kill-window #W? (y/n)" kill-window
bind -n C-M-down kill-window
bind -n M-up new-window
bind -n M-left previous-window
bind -n M-right next-window

# Swapping window positions
bind -n S-M-left swap-window -d -t -1
bind -n S-M-right swap-window -d -t +1

# Switch between windows with Alt + 1/2/3...
bind -n M-0 select-window -t :0
bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9

# Panes management
bind | split-window -h -c "#{pane_current_path}"
bind \\ split-window -v -c "#{pane_current_path}"

# Quick detach
bind -n M-d detach

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

###########################################################
# Theme and statusbar
###########################################################
# https://github.com/catppuccin/tmux/blob/main/themes/catppuccin_mocha_tmux.conf
# --> Catppuccin (Mocha) 
set -ogq @thm_bg "#1e1e2e"
set -ogq @thm_fg "#cdd6f4"

# Colors
set -ogq @thm_rosewater "#f5e0dc"
set -ogq @thm_flamingo "#f2cdcd"
set -ogq @thm_pink "#f5c2e7"
set -ogq @thm_mauve "#cba6f7"
set -ogq @thm_red "#f38ba8"
set -ogq @thm_maroon "#eba0ac"
set -ogq @thm_peach "#fab387"
set -ogq @thm_yellow "#f9e2af"
set -ogq @thm_green "#a6e3a1"
set -ogq @thm_teal "#94e2d5"
set -ogq @thm_sky "#89dceb"
set -ogq @thm_sapphire "#74c7ec"
set -ogq @thm_blue "#89b4fa"
set -ogq @thm_lavender "#b4befe"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#a6adc8"
set -ogq @thm_subtext_0 "#bac2de"
set -ogq @thm_overlay_2 "#9399b2"
set -ogq @thm_overlay_1 "#7f849c"
set -ogq @thm_overlay_0 "#6c7086"
set -ogq @thm_surface_2 "#585b70"
set -ogq @thm_surface_1 "#45475a"
set -ogq @thm_surface_0 "#313244"
set -ogq @thm_mantle "#181825"
set -ogq @thm_crust "#11111b"

# Status bar colors and style
set -g status-style "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g status-left-length 100
set -g status-right-length 100

# Message style
set -g message-style "bg=#{@thm_bg},fg=#{@thm_red},bold"

# Pane format
set -g pane-border-style "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g pane-active-border-style "bg=#{@thm_bg},fg=#{@thm_mauve},bold"

# Status left 
set -g status-left ""

# Window status format
set -g window-status-format "#[bg=#{@thm_bg},fg=#{@thm_fg}] #I:#W "
set -g window-status-current-format "#[bg=#{@thm_bg},fg=#{@thm_mauve},bold] #I:#W "

# Status right 
set -g status-right " \
#[bg=#{@thm_bg},fg=#{@thm_fg}]| \
#[bg=#{@thm_bg},fg=#{@thm_sapphire}]CAL #[bg=#{@thm_bg},fg=#{@thm_fg}]#(date +%m/%d/%Y) \
#[bg=#{@thm_bg},fg=#{@thm_fg}]| \
#[bg=#{@thm_bg},fg=#{@thm_sapphire}]CLK #[bg=#{@thm_bg},fg=#{@thm_fg}]#(date +%I:%M%p) "

